# Generated by Django 5.0.6 on 2024-06-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_coin_favourite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
